# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twtr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_user',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitter_user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitter_user',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitter_user',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
