# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twtr', '0002_auto_20180329_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_user',
            name='user_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
