# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twtr', '0004_auto_20180329_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_user',
            name='latitude',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='twitter_user',
            name='longitude',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
