# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twtr', '0005_auto_20180329_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_user',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='twitter_user',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
    ]
