# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-30 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twtr', '0006_auto_20180329_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_user',
            name='user_since',
            field=models.DateTimeField(null=True),
        ),
    ]
